juno branch

diff --git a/functions b/functions
--- a/functions
+++ b/functions
@@ -1,5 +1,3 @@
-#!/bin/bash
-#
 # functions - DevStack-specific functions
 #
 # The following variables are assumed to be defined by certain functions:
@@ -10,19 +8,12 @@
 # - ``GLANCE_HOSTPORT``
 #
 
-# ensure we don't re-source this in the same environment
-[[ -z "$_DEVSTACK_FUNCTIONS" ]] || return 0
-declare -r _DEVSTACK_FUNCTIONS=1
-
 # Include the common functions
 FUNC_DIR=$(cd $(dirname "${BASH_SOURCE:-$0}") && pwd)
 source ${FUNC_DIR}/functions-common
-source ${FUNC_DIR}/inc/ini-config
-source ${FUNC_DIR}/inc/python
-source ${FUNC_DIR}/inc/rootwrap
 
 # Save trace setting
-_XTRACE_FUNCTIONS=$(set +o | grep xtrace)
+XTRACE=$(set +o | grep xtrace)
 set +o xtrace
 
 # Check if a function already exists
@@ -36,9 +27,10 @@ function function_exists {
 # - ``FILES`` must be set to the cache dir
 # - ``GLANCE_HOSTPORT``
 #
-# upload_image image-url
+# upload_image image-url glance-token
 function upload_image {
     local image_url=$1
+    local token=$2
 
     local image image_fname image_name
 
@@ -48,7 +40,7 @@ function upload_image {
     if [[ $image_url != file* ]]; then
         # Downloads the image (uec ami+akistyle), then extracts it.
         if [[ ! -f $FILES/$image_fname || "$(stat -c "%s" $FILES/$image_fname)" = "0" ]]; then
-            wget --progress=dot:giga -c $image_url -O $FILES/$image_fname
+            wget -c $image_url -O $FILES/$image_fname
             if [[ $? -ne 0 ]]; then
                 echo "Not found: $image_url"
                 return
@@ -70,7 +62,7 @@ function upload_image {
     # OpenVZ-format images are provided as .tar.gz, but not decompressed prior to loading
     if [[ "$image_url" =~ 'openvz' ]]; then
         image_name="${image_fname%.tar.gz}"
-        openstack --os-cloud=devstack-admin image create "$image_name" --public --container-format ami --disk-format ami < "${image}"
+        openstack --os-token $token --os-url $GLANCE_SERVICE_PROTOCOL://$GLANCE_HOSTPORT image create "$image_name" --public --container-format ami --disk-format ami < "${image}"
         return
     fi
 
@@ -90,7 +82,7 @@ function upload_image {
         # driver will supply default values.
 
         local vmdk_disktype=""
-        local vmdk_net_adapter="e1000"
+        local vmdk_net_adapter=""
         local path_len
 
         # vmdk adapter type
@@ -122,7 +114,7 @@ function upload_image {
             if [[ $flat_url != file* ]]; then
                 if [[ ! -f $FILES/$flat_fname || \
                 "$(stat -c "%s" $FILES/$flat_fname)" = "0" ]]; then
-                    wget --progress=dot:giga -c $flat_url -O $FILES/$flat_fname
+                    wget -c $flat_url -O $FILES/$flat_fname
                 fi
                 image="$FILES/${flat_fname}"
             else
@@ -181,7 +173,7 @@ function upload_image {
         vmdk_adapter_type="${props[1]:-$vmdk_adapter_type}"
         vmdk_net_adapter="${props[2]:-$vmdk_net_adapter}"
 
-        openstack --os-cloud=devstack-admin image create "$image_name" --public --container-format bare --disk-format vmdk --property vmware_disktype="$vmdk_disktype" --property vmware_adaptertype="$vmdk_adapter_type" --property hw_vif_model="$vmdk_net_adapter" < "${image}"
+        openstack --os-token $token --os-url $GLANCE_SERVICE_PROTOCOL://$GLANCE_HOSTPORT image create "$image_name" --public --container-format bare --disk-format vmdk --property vmware_disktype="$vmdk_disktype" --property vmware_adaptertype="$vmdk_adapter_type" --property hw_vif_model="$vmdk_net_adapter" < "${image}"
         return
     fi
 
@@ -198,7 +190,8 @@ function upload_image {
             force_vm_mode="--property vm_mode=xen"
         fi
         openstack \
-            --os-cloud=devstack-admin \
+            --os-token $token \
+            --os-url $GLANCE_SERVICE_PROTOCOL://$GLANCE_HOSTPORT \
             image create \
             "$image_name" --public \
             --container-format=ovf --disk-format=vhd \
@@ -212,27 +205,12 @@ function upload_image {
     if [[ "$image_url" =~ '.xen-raw.tgz' ]]; then
         image_name="${image_fname%.xen-raw.tgz}"
         openstack \
-            --os-cloud=devstack-admin \
+            --os-token $token \
+            --os-url $GLANCE_SERVICE_PROTOCOL://$GLANCE_HOSTPORT \
             image create \
             "$image_name" --public \
             --container-format=tgz --disk-format=raw \
             --property vm_mode=xen < "${image}"
-        return
-    fi
-
-    if [[ "$image_url" =~ '.hds' ]]; then
-        image_name="${image_fname%.hds}"
-        vm_mode=${image_name##*-}
-        if [[ $vm_mode != 'exe' && $vm_mode != 'hvm' ]]; then
-            die $LINENO "Unknown vm_mode=${vm_mode} for Virtuozzo image"
-        fi
-
-        openstack \
-            --os-cloud=devstack-admin \
-            image create \
-            "$image_name" --public \
-            --container-format=bare --disk-format=ploop \
-            --property vm_mode=$vm_mode < "${image}"
         return
     fi
 
@@ -264,8 +242,7 @@ function upload_image {
             ;;
         *.img)
             image_name=$(basename "$image" ".img")
-            local format
-            format=$(qemu-img info ${image} | awk '/^file format/ { print $3; exit }')
+            local format=$(qemu-img info ${image} | awk '/^file format/ { print $3; exit }')
             if [[ ",qcow2,raw,vdi,vmdk,vpc," =~ ",$format," ]]; then
                 disk_format=$format
             else
@@ -305,15 +282,11 @@ function upload_image {
         img_property="--property hw_cdrom_bus=scsi"
     fi
 
-    if is_arch "aarch64"; then
-        img_property="--property hw_machine_type=virt --property hw_cdrom_bus=virtio --property os_command_line='console=ttyAMA0'"
-    fi
-
     if [ "$container_format" = "bare" ]; then
         if [ "$unpack" = "zcat" ]; then
-            openstack --os-cloud=devstack-admin image create "$image_name" $img_property --public --container-format=$container_format --disk-format $disk_format < <(zcat --force "${image}")
+            openstack --os-token $token --os-url $GLANCE_SERVICE_PROTOCOL://$GLANCE_HOSTPORT image create "$image_name" $img_property --public --container-format=$container_format --disk-format $disk_format < <(zcat --force "${image}")
         else
-            openstack --os-cloud=devstack-admin image create "$image_name" $img_property --public --container-format=$container_format --disk-format $disk_format < "${image}"
+            openstack --os-token $token --os-url $GLANCE_SERVICE_PROTOCOL://$GLANCE_HOSTPORT image create "$image_name" $img_property --public --container-format=$container_format --disk-format $disk_format < "${image}"
         fi
     else
         # Use glance client to add the kernel the root filesystem.
@@ -321,12 +294,12 @@ function upload_image {
         # kernel for use when uploading the root filesystem.
         local kernel_id="" ramdisk_id="";
         if [ -n "$kernel" ]; then
-            kernel_id=$(openstack --os-cloud=devstack-admin image create "$image_name-kernel" $img_property --public --container-format aki --disk-format aki < "$kernel" | grep ' id ' | get_field 2)
+            kernel_id=$(openstack --os-token $token --os-url $GLANCE_SERVICE_PROTOCOL://$GLANCE_HOSTPORT image create "$image_name-kernel" $img_property --public --container-format aki --disk-format aki < "$kernel" | grep ' id ' | get_field 2)
         fi
         if [ -n "$ramdisk" ]; then
-            ramdisk_id=$(openstack --os-cloud=devstack-admin image create "$image_name-ramdisk" $img_property --public --container-format ari --disk-format ari < "$ramdisk" | grep ' id ' | get_field 2)
+            ramdisk_id=$(openstack --os-token $token --os-url $GLANCE_SERVICE_PROTOCOL://$GLANCE_HOSTPORT image create "$image_name-ramdisk" $img_property --public --container-format ari --disk-format ari < "$ramdisk" | grep ' id ' | get_field 2)
         fi
-        openstack --os-cloud=devstack-admin image create "${image_name%.img}" $img_property --public --container-format ami --disk-format ami ${kernel_id:+--property kernel_id=$kernel_id} ${ramdisk_id:+--property ramdisk_id=$ramdisk_id} < "${image}"
+        openstack --os-token $token --os-url $GLANCE_SERVICE_PROTOCOL://$GLANCE_HOSTPORT image create "${image_name%.img}" $img_property --public --container-format ami --disk-format ami ${kernel_id:+--property kernel_id=$kernel_id} ${ramdisk_id:+--property ramdisk_id=$ramdisk_id} < "${image}"
     fi
 }
 
@@ -342,62 +315,57 @@ function use_database {
         # No backends registered means this is likely called from ``localrc``
         # This is now deprecated usage
         DATABASE_TYPE=$1
-        deprecated "The database backend needs to be properly set in ENABLED_SERVICES; use_database is deprecated localrc"
+        DEPRECATED_TEXT="$DEPRECATED_TEXT\nThe database backend needs to be properly set in ENABLED_SERVICES; use_database is deprecated localrc\n"
     else
         # This should no longer get called...here for posterity
         use_exclusive_service DATABASE_BACKENDS DATABASE_TYPE $1
     fi
 }
 
-#Macro for curl statements. curl requires -g option for literal IPv6 addresses.
-CURL_GET="${CURL_GET:-curl -g}"
 
 # Wait for an HTTP server to start answering requests
 # wait_for_service timeout url
 function wait_for_service {
     local timeout=$1
     local url=$2
-    timeout $timeout sh -c "while ! $CURL_GET -k --noproxy '*' -s $url >/dev/null; do sleep 1; done"
+    timeout $timeout sh -c "while ! curl -k --noproxy '*' -s $url >/dev/null; do sleep 1; done"
 }
 
 
 # ping check
-# Uses globals ``ENABLED_SERVICES``, ``TOP_DIR``, ``MULTI_HOST``, ``PRIVATE_NETWORK``
-# ping_check <ip> [boot-timeout] [from_net] [expected]
+# Uses globals ``ENABLED_SERVICES``
+# ping_check from-net ip boot-timeout expected
 function ping_check {
-    local ip=$1
-    local timeout=${2:-30}
-    local from_net=${3:-""}
-    local expected=${4:-True}
-    local op="!"
-    local failmsg="[Fail] Couldn't ping server"
-    local ping_cmd="ping"
+    if is_service_enabled neutron; then
+        _ping_check_neutron  "$1" $2 $3 $4
+        return
+    fi
+    _ping_check_novanet "$1" $2 $3 $4
+}
 
-    # if we don't specify a from_net we're expecting things to work
-    # fine from our local box.
-    if [[ -n "$from_net" ]]; then
-        if is_service_enabled neutron; then
-            ping_cmd="$TOP_DIR/tools/ping_neutron.sh $from_net"
-        elif [[ "$MULTI_HOST" = "True" && "$from_net" = "$PRIVATE_NETWORK_NAME" ]]; then
-            # there is no way to address the multihost / private case, bail here for compatibility.
-            # TODO: remove this cruft and redo code to handle this at the caller level.
-            return
+# ping check for nova
+# Uses globals ``MULTI_HOST``, ``PRIVATE_NETWORK``
+function _ping_check_novanet {
+    local from_net=$1
+    local ip=$2
+    local boot_timeout=$3
+    local expected=${4:-"True"}
+    local check_command=""
+    MULTI_HOST=`trueorfalse False $MULTI_HOST`
+    if [[ "$MULTI_HOST" = "True" && "$from_net" = "$PRIVATE_NETWORK_NAME" ]]; then
+        return
+    fi
+    if [[ "$expected" = "True" ]]; then
+        check_command="while ! ping -c1 -w1 $ip; do sleep 1; done"
+    else
+        check_command="while ping -c1 -w1 $ip; do sleep 1; done"
+    fi
+    if ! timeout $boot_timeout sh -c "$check_command"; then
+        if [[ "$expected" = "True" ]]; then
+            die $LINENO "[Fail] Couldn't ping server"
+        else
+            die $LINENO "[Fail] Could ping server"
         fi
-    fi
-
-    # inverse the logic if we're testing no connectivity
-    if [[ "$expected" != "True" ]]; then
-        op=""
-        failmsg="[Fail] Could ping server"
-    fi
-
-    # Because we've transformed this command so many times, print it
-    # out at the end.
-    local check_command="while $op $ping_cmd -c1 -w1 $ip; do sleep 1; done"
-    echo "Checking connectivity with $check_command"
-
-    if ! timeout $timeout sh -c "$check_command"; then
-        die $LINENO $failmsg
     fi
 }
 
@@ -406,11 +374,10 @@ function get_instance_ip {
     local vm_id=$1
     local network_name=$2
     local nova_result="$(nova show $vm_id)"
-    local ip
-    ip=$(echo "$nova_result" | grep "$network_name" | get_field 2)
+    local ip=$(echo "$nova_result" | grep "$network_name" | get_field 2)
     if [[ $ip = "" ]];then
         echo "$nova_result"
-        die $LINENO "[Fail] Couldn't get ipaddress of VM"
+        die $LINENO "[Fail] Coudn't get ipaddress of VM"
     fi
     echo $ip
 }
@@ -457,8 +424,7 @@ function check_path_perm_sanity {
     # homedir permissions on RHEL and common practice of making DEST in
     # the stack user's homedir.
 
-    local real_path
-    real_path=$(readlink -f $1)
+    local real_path=$(readlink -f $1)
     local rebuilt_path=""
     for i in $(echo ${real_path} | tr "/" " "); do
         rebuilt_path=$rebuilt_path"/"$i
@@ -467,7 +433,7 @@ function check_path_perm_sanity {
             echo "*** DEST path element"
             echo "***    ${rebuilt_path}"
             echo "*** appears to have 0700 permissions."
-            echo "*** This is very likely to cause fatal issues for DevStack daemons."
+            echo "*** This is very likely to cause fatal issues for devstack daemons."
 
             if [[ -n "$SKIP_PATH_SANITY" ]]; then
                 return
@@ -554,8 +520,8 @@ function setup_colorized_logging {
 }
 
 # These functions are provided for basic fall-back functionality for
-# projects that include parts of DevStack (Grenade).  stack.sh will
-# override these with more specific versions for DevStack (with fancy
+# projects that include parts of devstack (grenade).  stack.sh will
+# override these with more specific versions for devstack (with fancy
 # spinners, etc).  We never override an existing version
 if ! function_exists echo_summary; then
     function echo_summary {
@@ -603,7 +569,7 @@ function create_disk {
 }
 
 # Restore xtrace
-$_XTRACE_FUNCTIONS
+$XTRACE
 
 # Local variables:
 # mode: shell-script
diff --git a/lib/nova_plugins/functions-libvirt b/lib/nova_plugins/functions-libvirt
--- a/lib/nova_plugins/functions-libvirt
+++ b/lib/nova_plugins/functions-libvirt
@@ -1,5 +1,3 @@
-#!/bin/bash
-#
 # lib/nova_plugins/functions-libvirt
 # Common libvirt configuration functions
 
@@ -8,46 +6,39 @@
 # ``STACK_USER`` has to be defined
 
 # Save trace setting
-_XTRACE_NOVA_FN_LIBVIRT=$(set +o | grep xtrace)
+LV_XTRACE=$(set +o | grep xtrace)
 set +o xtrace
 
 # Defaults
 # --------
 
-# Turn on selective debug log filters for libvirt.
-# (NOTE: Enabling this by default, because the log filters enabled in
-# 'configure_libvirt' function further below are _selective_ and not
-# extremely verbose.)
-DEBUG_LIBVIRT=$(trueorfalse True DEBUG_LIBVIRT)
+# if we should turn on massive libvirt debugging
+DEBUG_LIBVIRT=$(trueorfalse False $DEBUG_LIBVIRT)
 
 # Installs required distro-specific libvirt packages.
 function install_libvirt {
     if is_ubuntu; then
-        if is_arch "aarch64" && [[ ${DISTRO} == "trusty" ]]; then
-            install_package qemu-system
-        else
-            install_package qemu-kvm
-            install_package libguestfs0
-        fi
-        install_package libvirt-bin libvirt-dev
-        pip_install_gr libvirt-python
-        if [[ "$EBTABLES_RACE_FIX" == "True" ]]; then
-            # Work around for bug #1501558. We can remove this once we
-            # get to a version of Ubuntu that has new enough libvirt.
-            TOP_DIR=$TOP_DIR $TOP_DIR/tools/install_ebtables_workaround.sh
-        fi
-        #pip_install_gr <there-si-no-guestfs-in-pypi>
+        install_package qemu-kvm
+        install_package libvirt-bin
+        install_package python-libvirt
+        install_package python-guestfs
     elif is_fedora || is_suse; then
         install_package kvm
-        # there is a dependency issue with kvm (which is really just a
-        # wrapper to qemu-system-x86) that leaves some bios files out,
-        # so install qemu-kvm (which shouldn't strictly be needed, as
-        # everything has been merged into qemu-system-x86) to bring in
-        # the right packages. see
-        # https://bugzilla.redhat.com/show_bug.cgi?id=1235890
-        install_package qemu-kvm
-        install_package libvirt libvirt-devel
-        pip_install_gr libvirt-python
+        install_package libvirt
+        install_package libvirt-python
+        install_package python-libguestfs
+    fi
+
+    # Restart firewalld after install of libvirt to avoid a problem
+    # with polkit, which libvirtd brings in.  See
+    # https://bugzilla.redhat.com/show_bug.cgi?id=1099031
+
+    # Note there is a difference between F20 rackspace cloud images
+    # and HP images used in the gate; rackspace has firewalld but hp
+    # cloud doesn't.  RHEL6 doesn't have firewalld either.  So we
+    # don't care if it fails.
+    if is_fedora && is_package_installed firewalld; then
+        sudo service firewalld restart || true
     fi
 }
 
@@ -75,12 +66,34 @@ EOF
     fi
 
     if is_fedora || is_suse; then
-        # Starting with fedora 18 and opensuse-12.3 enable stack-user to
-        # virsh -c qemu:///system by creating a policy-kit rule for
-        # stack-user using the new Javascript syntax
-        rules_dir=/etc/polkit-1/rules.d
-        sudo mkdir -p $rules_dir
-        cat <<EOF | sudo tee $rules_dir/50-libvirt-$STACK_USER.rules
+        if is_fedora && [[ $DISTRO =~ (rhel6) || "$os_RELEASE" -le "17" ]]; then
+            cat <<EOF | sudo tee /etc/polkit-1/localauthority/50-local.d/50-libvirt-remote-access.pkla
+[libvirt Management Access]
+Identity=unix-group:$LIBVIRT_GROUP
+Action=org.libvirt.unix.manage
+ResultAny=yes
+ResultInactive=yes
+ResultActive=yes
+EOF
+        elif is_suse && [[ $os_RELEASE = 12.2 || "$os_VENDOR" = "SUSE LINUX" ]]; then
+            # openSUSE < 12.3 or SLE
+            # Work around the fact that polkit-default-privs overrules pklas
+            # with 'unix-group:$group'.
+            cat <<EOF | sudo tee /etc/polkit-1/localauthority/50-local.d/50-libvirt-remote-access.pkla
+[libvirt Management Access]
+Identity=unix-user:$STACK_USER
+Action=org.libvirt.unix.manage
+ResultAny=yes
+ResultInactive=yes
+ResultActive=yes
+EOF
+        else
+            # Starting with fedora 18 and opensuse-12.3 enable stack-user to
+            # virsh -c qemu:///system by creating a policy-kit rule for
+            # stack-user using the new Javascript syntax
+            rules_dir=/etc/polkit-1/rules.d
+            sudo mkdir -p $rules_dir
+            cat <<EOF | sudo tee $rules_dir/50-libvirt-$STACK_USER.rules
 polkit.addRule(function(action, subject) {
     if (action.id == 'org.libvirt.unix.manage' &&
         subject.user == '$STACK_USER') {
@@ -88,7 +101,8 @@ polkit.addRule(function(action, subject) {
     }
 });
 EOF
-        unset rules_dir
+            unset rules_dir
+        fi
     fi
 
     # The user that nova runs as needs to be member of **libvirtd** group otherwise
@@ -105,9 +119,9 @@ EOF
             # source file paths, not relative paths. This screws with the matching
             # of '1:libvirt' making everything turn on. So use libvirt.c for now.
             # This will have to be re-visited when Ubuntu ships libvirt >= 1.2.3
-            local log_filters="1:libvirt.c 1:qemu 1:conf 1:security 3:object 3:event 3:json 3:file 1:util 1:qemu_monitor"
+            local log_filters="1:libvirt.c 1:qemu 1:conf 1:security 3:object 3:event 3:json 3:file 1:util"
         else
-            local log_filters="1:libvirt 1:qemu 1:conf 1:security 3:object 3:event 3:json 3:file 1:util 1:qemu_monitor"
+            local log_filters="1:libvirt 1:qemu 1:conf 1:security 3:object 3:event 3:json 3:file 1:util"
         fi
         local log_outputs="1:file:/var/log/libvirt/libvirtd.log"
         if ! grep -q "log_filters=\"$log_filters\"" /etc/libvirt/libvirtd.conf; then
@@ -118,23 +132,15 @@ EOF
         fi
     fi
 
-    # Update the libvirt cpu map with a gate64 cpu model. This enables nova
-    # live migration for 64bit guest OSes on heterogenous cloud "hardware".
-    if [[ -f /usr/share/libvirt/cpu_map.xml ]] ; then
-        sudo $TOP_DIR/tools/cpu_map_update.py /usr/share/libvirt/cpu_map.xml
-    fi
-
     # libvirt detects various settings on startup, as we potentially changed
     # the system configuration (modules, filesystems), we need to restart
-    # libvirt to detect those changes. Use a stop start as otherwise the new
-    # cpu_map is not loaded properly on some systems (Ubuntu).
-    stop_service $LIBVIRT_DAEMON
-    start_service $LIBVIRT_DAEMON
+    # libvirt to detect those changes.
+    restart_service $LIBVIRT_DAEMON
 }
 
 
 # Restore xtrace
-$_XTRACE_NOVA_FN_LIBVIRT
+$LV_XTRACE
 
 # Local variables:
 # mode: shell-script
diff --git a/lib/rpc_backend b/lib/rpc_backend
--- a/lib/rpc_backend
+++ b/lib/rpc_backend
@@ -1,31 +1,65 @@
-#!/bin/bash
-#
 # lib/rpc_backend
-# Interface for installing RabbitMQ on the system
+# Interface for interactig with different rpc backend
+# rpc backend settings
 
 # Dependencies:
 #
 # - ``functions`` file
-# - ``RABBIT_{HOST|PASSWORD|USERID}`` must be defined when RabbitMQ is used
+# - ``RABBIT_{HOST|PASSWORD}`` must be defined when RabbitMQ is used
+# - ``RPC_MESSAGING_PROTOCOL`` option for configuring the messaging protocol
 
 # ``stack.sh`` calls the entry points in this order:
 #
 # - check_rpc_backend
 # - install_rpc_backend
 # - restart_rpc_backend
-# - iniset_rpc_backend (stable interface)
-#
-# Note: if implementing an out of tree plugin for an RPC backend, you
-# should install all services through normal plugin methods, then
-# redefine ``iniset_rpc_backend`` in your code. That's the one portion
-# of this file which is a standard interface.
+# - iniset_rpc_backend
 
 # Save trace setting
-_XTRACE_RPC_BACKEND=$(set +o | grep xtrace)
+XTRACE=$(set +o | grep xtrace)
 set +o xtrace
+
 
 # Functions
 # ---------
+
+
+# Make sure we only have one rpc backend enabled.
+# Also check the specified rpc backend is available on your platform.
+function check_rpc_backend {
+    local c svc
+
+    local rpc_needed=1
+    # We rely on the fact that filenames in lib/* match the service names
+    # that can be passed as arguments to is_service_enabled.
+    # We check for a call to iniset_rpc_backend in these files, meaning
+    # the service needs a backend.
+    rpc_candidates=$(grep -rl iniset_rpc_backend $TOP_DIR/lib/ | awk -F/ '{print $NF}')
+    for c in ${rpc_candidates}; do
+        if is_service_enabled $c; then
+            rpc_needed=0
+            break
+        fi
+    done
+    local rpc_backend_cnt=0
+    for svc in qpid zeromq rabbit; do
+        is_service_enabled $svc &&
+        (( rpc_backend_cnt++ )) || true
+    done
+    if [ "$rpc_backend_cnt" -gt 1 ]; then
+        echo "ERROR: only one rpc backend may be enabled,"
+        echo "       set only one of 'rabbit', 'qpid', 'zeromq'"
+        echo "       via ENABLED_SERVICES."
+    elif [ "$rpc_backend_cnt" == 0 ] && [ "$rpc_needed" == 0 ]; then
+        echo "ERROR: at least one rpc backend must be enabled,"
+        echo "       set one of 'rabbit', 'qpid', 'zeromq'"
+        echo "       via ENABLED_SERVICES."
+    fi
+
+    if is_service_enabled qpid && ! qpid_is_supported; then
+        die $LINENO "Qpid support is not available for this version of your distribution."
+    fi
+}
 
 # clean up after rpc backend - eradicate all traces so changing backends
 # produces a clean switch
@@ -33,20 +67,125 @@ function cleanup_rpc_backend {
     if is_service_enabled rabbit; then
         # Obliterate rabbitmq-server
         uninstall_package rabbitmq-server
-        # in case it's not actually running, /bin/true at the end
-        sudo killall epmd || sudo killall -9 epmd || /bin/true
+        sudo killall epmd || sudo killall -9 epmd
         if is_ubuntu; then
             # And the Erlang runtime too
             apt_get purge -y erlang*
         fi
+    elif is_service_enabled qpid; then
+        if is_fedora; then
+            uninstall_package qpid-cpp-server
+        elif is_ubuntu; then
+            uninstall_package qpidd
+        else
+            exit_distro_not_supported "qpid installation"
+        fi
+    elif is_service_enabled zeromq; then
+        if is_fedora; then
+            uninstall_package zeromq python-zmq redis
+        elif is_ubuntu; then
+            uninstall_package libzmq1 python-zmq redis-server
+        elif is_suse; then
+            uninstall_package libzmq1 python-pyzmq redis
+        else
+            exit_distro_not_supported "zeromq installation"
+        fi
+    fi
+
+    # Remove the AMQP 1.0 messaging libraries
+    if [ "$RPC_MESSAGING_PROTOCOL" == "AMQP1" ]; then
+        if is_fedora; then
+            uninstall_package qpid-proton-c-devel
+            uninstall_package python-qpid-proton
+        fi
+        # TODO(kgiusti) ubuntu cleanup
     fi
 }
 
 # install rpc backend
 function install_rpc_backend {
+    # Regardless of the broker used, if AMQP 1.0 is configured load
+    # the necessary messaging client libraries for oslo.messaging
+    if [ "$RPC_MESSAGING_PROTOCOL" == "AMQP1" ]; then
+        if is_fedora; then
+            install_package qpid-proton-c-devel
+            install_package python-qpid-proton
+        elif is_ubuntu; then
+            # TODO(kgiusti) The QPID AMQP 1.0 protocol libraries
+            # are not yet in the ubuntu repos. Enable these installs
+            # once they are present:
+            #install_package libqpid-proton2-dev
+            #install_package python-qpid-proton
+            # Also add 'uninstall' directives in cleanup_rpc_backend()!
+            exit_distro_not_supported "QPID AMQP 1.0 Proton libraries"
+        else
+            exit_distro_not_supported "QPID AMQP 1.0 Proton libraries"
+        fi
+        # Install pyngus client API
+        # TODO(kgiusti) can remove once python qpid bindings are
+        # available on all supported platforms _and_ pyngus is added
+        # to the requirements.txt file in oslo.messaging
+        pip_install_gr pyngus
+    fi
+
     if is_service_enabled rabbit; then
         # Install rabbitmq-server
         install_package rabbitmq-server
+    elif is_service_enabled qpid; then
+        local qpid_conf_file=/etc/qpid/qpidd.conf
+        if is_fedora; then
+            install_package qpid-cpp-server
+            if [[ $DISTRO =~ (rhel6) ]]; then
+                qpid_conf_file=/etc/qpidd.conf
+                # RHEL6 leaves "auth=yes" in /etc/qpidd.conf, it needs to
+                # be no or you get GSS authentication errors as it
+                # attempts to default to this.
+                sudo sed -i.bak 's/^auth=yes$/auth=no/' $qpid_conf_file
+            fi
+        elif is_ubuntu; then
+            install_package qpidd
+            sudo sed -i '/PLAIN/!s/mech_list: /mech_list: PLAIN /' /etc/sasl2/qpidd.conf
+            sudo chmod o+r /etc/qpid/qpidd.sasldb
+        else
+            exit_distro_not_supported "qpid installation"
+        fi
+        # If AMQP 1.0 is specified, ensure that the version of the
+        # broker can support AMQP 1.0 and configure the queue and
+        # topic address patterns used by oslo.messaging.
+        if [ "$RPC_MESSAGING_PROTOCOL" == "AMQP1" ]; then
+            QPIDD=$(type -p qpidd)
+            if ! $QPIDD --help | grep -q "queue-patterns"; then
+                exit_distro_not_supported "qpidd with AMQP 1.0 support"
+            fi
+            if ! grep -q "queue-patterns=exclusive" $qpid_conf_file; then
+                cat <<EOF | sudo tee --append $qpid_conf_file
+queue-patterns=exclusive
+queue-patterns=unicast
+topic-patterns=broadcast
+EOF
+            fi
+        fi
+    elif is_service_enabled zeromq; then
+        # NOTE(ewindisch): Redis is not strictly necessary
+        # but there is a matchmaker driver that works
+        # really well & out of the box for multi-node.
+        if is_fedora; then
+            install_package zeromq python-zmq redis
+        elif is_ubuntu; then
+            install_package libzmq1 python-zmq redis-server
+        elif is_suse; then
+            install_package libzmq1 python-pyzmq redis
+        else
+            exit_distro_not_supported "zeromq installation"
+        fi
+        # Necessary directory for socket location.
+        sudo mkdir -p /var/run/openstack
+        sudo chown $STACK_USER /var/run/openstack
+    fi
+
+    # If using the QPID broker, install the QPID python client API
+    if is_service_enabled qpid || [ -n "$QPID_HOST" ]; then
+        install_package python-qpid
     fi
 }
 
@@ -57,91 +196,76 @@ function restart_rpc_backend {
         echo_summary "Starting RabbitMQ"
         # NOTE(bnemec): Retry initial rabbitmq configuration to deal with
         # the fact that sometimes it fails to start properly.
-        # Reference: https://bugzilla.redhat.com/show_bug.cgi?id=1144100
-        # NOTE(tonyb): Extend the original retry logic to only restart rabbitmq
-        # every second time around the loop.
-        # See: https://bugs.launchpad.net/devstack/+bug/1449056 for details on
-        # why this is needed.  This can bee seen on vivid and Debian unstable
-        # (May 2015)
-        # TODO(tonyb): Remove this when Debian and Ubuntu have a fixed systemd
-        # service file.
+        # Reference: https://bugzilla.redhat.com/show_bug.cgi?id=1059028
         local i
-        for i in `seq 20`; do
-            local rc=0
-
-            [[ $i -eq "20" ]] && die $LINENO "Failed to set rabbitmq password"
-
-            if [[ $(( i % 2 )) == "0" ]] ; then
+        for i in `seq 10`; do
+            if is_fedora || is_suse; then
+                # service is not started by default
                 restart_service rabbitmq-server
             fi
-
-            rabbit_setuser "$RABBIT_USERID" "$RABBIT_PASSWORD" || rc=$?
-            if [ $rc -ne 0 ]; then
-                continue
-            fi
-
             # change the rabbit password since the default is "guest"
-            sudo rabbitmqctl change_password \
-                $RABBIT_USERID $RABBIT_PASSWORD || rc=$?
-            if [ $rc -ne 0 ]; then
-                continue;
-            fi
-
-            break
+            sudo rabbitmqctl change_password guest $RABBIT_PASSWORD && break
+            [[ $i -eq "10" ]] && die $LINENO "Failed to set rabbitmq password"
         done
         if is_service_enabled n-cell; then
             # Add partitioned access for the child cell
             if [ -z `sudo rabbitmqctl list_vhosts | grep child_cell` ]; then
                 sudo rabbitmqctl add_vhost child_cell
-                sudo rabbitmqctl set_permissions -p child_cell $RABBIT_USERID ".*" ".*" ".*"
+                sudo rabbitmqctl set_permissions -p child_cell guest ".*" ".*" ".*"
             fi
         fi
+    elif is_service_enabled qpid; then
+        echo_summary "Starting qpid"
+        restart_service qpidd
     fi
 }
 
-# builds transport url string
-function get_transport_url {
-    if is_service_enabled rabbit || { [ -n "$RABBIT_HOST" ] && [ -n "$RABBIT_PASSWORD" ]; }; then
-        echo "rabbit://$RABBIT_USERID:$RABBIT_PASSWORD@$RABBIT_HOST:5672/"
-    fi
-}
-
-# iniset configuration
+# iniset cofiguration
 function iniset_rpc_backend {
     local package=$1
     local file=$2
-    local section=${3:-DEFAULT}
-    if is_service_enabled rabbit || { [ -n "$RABBIT_HOST" ] && [ -n "$RABBIT_PASSWORD" ]; }; then
-        iniset $file $section rpc_backend "rabbit"
-        iniset $file oslo_messaging_rabbit rabbit_hosts $RABBIT_HOST
-        iniset $file oslo_messaging_rabbit rabbit_password $RABBIT_PASSWORD
-        iniset $file oslo_messaging_rabbit rabbit_userid $RABBIT_USERID
-        if [ -n "$RABBIT_HEARTBEAT_TIMEOUT_THRESHOLD" ]; then
-            iniset $file oslo_messaging_rabbit heartbeat_timeout_threshold $RABBIT_HEARTBEAT_TIMEOUT_THRESHOLD
+    local section=$3
+    if is_service_enabled zeromq; then
+        iniset $file $section rpc_backend ${package}.openstack.common.rpc.impl_zmq
+        iniset $file $section rpc_zmq_matchmaker \
+            ${package}.openstack.common.rpc.matchmaker_redis.MatchMakerRedis
+        # Set MATCHMAKER_REDIS_HOST if running multi-node.
+        MATCHMAKER_REDIS_HOST=${MATCHMAKER_REDIS_HOST:-127.0.0.1}
+        iniset $file matchmaker_redis host $MATCHMAKER_REDIS_HOST
+    elif is_service_enabled qpid || [ -n "$QPID_HOST" ]; then
+        # For Qpid use the 'amqp' oslo.messaging transport when AMQP 1.0 is used
+        if [ "$RPC_MESSAGING_PROTOCOL" == "AMQP1" ]; then
+            iniset $file $section rpc_backend "amqp"
+        else
+            iniset $file $section rpc_backend ${package}.openstack.common.rpc.impl_qpid
         fi
-        if [ -n "$RABBIT_HEARTBEAT_RATE" ]; then
-            iniset $file oslo_messaging_rabbit heartbeat_rate $RABBIT_HEARTBEAT_RATE
+        iniset $file $section qpid_hostname ${QPID_HOST:-$SERVICE_HOST}
+        if is_ubuntu; then
+            QPID_PASSWORD=`sudo strings /etc/qpid/qpidd.sasldb | grep -B1 admin | head -1`
+            iniset $file $section qpid_password $QPID_PASSWORD
+            iniset $file $section qpid_username admin
         fi
+    elif is_service_enabled rabbit || { [ -n "$RABBIT_HOST" ] && [ -n "$RABBIT_PASSWORD" ]; }; then
+        iniset $file $section rpc_backend ${package}.openstack.common.rpc.impl_kombu
+        iniset $file $section rabbit_hosts $RABBIT_HOST
+        iniset $file $section rabbit_password $RABBIT_PASSWORD
     fi
 }
 
-function rabbit_setuser {
-    local user="$1" pass="$2" found="" out=""
-    out=$(sudo rabbitmqctl list_users) ||
-        { echo "failed to list users" 1>&2; return 1; }
-    found=$(echo "$out" | awk '$1 == user { print $1 }' "user=$user")
-    if [ "$found" = "$user" ]; then
-        sudo rabbitmqctl change_password "$user" "$pass" ||
-            { echo "failed changing pass for '$user'" 1>&2; return 1; }
-    else
-        sudo rabbitmqctl add_user "$user" "$pass" ||
-            { echo "failed changing pass for $user"; return 1; }
+# Check if qpid can be used on the current distro.
+# qpid_is_supported
+function qpid_is_supported {
+    if [[ -z "$DISTRO" ]]; then
+        GetDistro
     fi
-    sudo rabbitmqctl set_permissions "$user" ".*" ".*" ".*"
+
+    # Qpid is not in openSUSE
+    ( ! is_suse )
 }
+
 
 # Restore xtrace
-$_XTRACE_RPC_BACKEND
+$XTRACE
 
 # Tell emacs to use shell-script-mode
 ## Local variables:
